version: "2"
services:

  wordpress:
    image: mysecure-wordpress
    build: .
    links:
      - db:mysql
    networks:
      - mysecure-wordpress
    ports:
      - 80:80
    restart: always
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_DB_NAME: wordpress

  db:
    image: mysql:latest
    volumes:
      - wpdb-data:/var/lib/mysql
    networks:
        - myssl-wordpress
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: example
volumes:
    wpdb-data:

networks:
  myssl-wordpress:
